name: netlify-plugin-health-check
inputs:
  - name: staticScripts
    description: Array of script URLs or filenames to check for in the HTML as static script tags
    required: false
    default: []

  - name: dynamicScripts
    description: Array of objects containing domain and pattern for scripts that are dynamically loaded. Format - [{domain: "analytics.segment.crossroads.net", pattern: "analytics\\.load\\(['\\"]"}]
    required: false
    default: []

  - name: checkFiles
    description: Array of file paths to check for scripts (relative to _site directory)
    required: false
    default: ["index.html"]
