module.exports = [
  {
    name: "application",
    deps: ["vendor/jquery-3.3.1.min"],
    files: ["components/analytics"],
  },
  {
    name: "application_deferred",
    deps: [
      "vendor/bootstrap.min",
      "vendor/clipboard.min",
      "vendor/crds-card-carousel-v0.2.2.min",
      "vendor/crds-jumbotron-video-v0.2.1.min",
      "vendor/crds-status-message-v0.1.3.min",
      "vendor/feature-flags.min",
      "vendor/flickity.pkgd.min",
      "vendor/imgix-optimizer-0.0.10.min",
      "vendor/imgix.min",
      "vendor/isotope.min",
      "vendor/knockout-3.4.2",
      "vendor/moment.min",
      "vendor/reactive-auth-v0.0.1.umd",
      "vendor/smart-app-banner-2.0.0.min",
      "vendor/webcomponents-lite.min",
    ],
    files: [
      "components/audio_video_toggler",
      "components/background-video",
      "components/carousels",
      "components/chat",
      "components/clipboard",
      "components/countdown",
      "components/dates",
      "components/discussion-questions",
      "components/filters",
      "components/global",
      "components/images",
      "components/jumbotron-video",
      "components/legacy-imgix",
      "components/menu-squencher",
      "components/pagination",
      "components/resi-player",
      "components/roll-call",
      "components/smart-banner",
      "components/status-message",
      "components/tabs",
      "components/toggle-tooltip",
      "components/track-viewport",
      "components/youtube",
      "lib/card-filters",
      "lib/data-tracker",
      "lib/distance-sorter",
      "lib/environment",
      "lib/height-watcher",
      "lib/location-finder",
      "lib/smooth-scroller",
    ],
  },
  {
    name: "preview_deferred",
    deps: [
      "vendor/bootstrap.min",
      "vendor/clipboard.min",
      "vendor/imgix-optimizer-0.0.10.min",
      "vendor/imgix.min",
      "vendor/marked",
    ],
    files: [
      "components/clipboard",
      "components/images",
      "components/menu-squencher",
      "components/preview",
    ],
  },
  {
    name: "bitmovin",
    deps: ["vendor/moment-2.24.min", "vendor/moment-timezone-0.5.25.min"],
    files: ["components/bitmovin"],
  },
  {
    name: "autoplay",
    files: ["components/autoplay-controller"],
  },
  {
    name: "parallax",
    files: ["vendor/rellax-1.10.0.min"],
  },
  {
    name: "masonry_deferred",
    files: ["components/masonry"],
  },
  {
    name: "reachout-trip",
    files: ["lib/reachout-trip"],
  },
  {
    name: "family-meeting-stream",
    files: ["views/family-meeting-stream"],
  },
  {
    name: "live",
    files: ["views/live"],
  },
  {
    name: "location-search",
    files: ["components/location-search"],
  },
  {
    name: "live-stream",
    deps: ["vendor/crds-rollcall-v1.0.1.min"],
    files: ["views/live-stream"],
  },
  {
    name: "explore",
    deps: [
      "vendor/animations.min",
      "vendor/jquery.fullPage-2.7.4.min",
      "vendor/tweenMax-1.18.0.min",
    ],
  },
  {
    name: "ash-wednesday-experience",
    deps: [
      "vendor/animations.min",
      "vendor/ash-wednesday-experience",
      "vendor/jquery.fullPage-2.7.4.min",
      "vendor/tweenMax-1.18.0.min",
    ],
  },
  {
    name: "events",
    files: [
      "vendor/events.min",
      "vendor/jquery.cycle2.min",
      "vendor/scrollVert.min",
    ],
  },
  {
    name: "skeleton",
    files: ["components/skeleton"],
  },
  {
    name: "video-modal-close",
    files: ["lib/video-modal-close"],
  },
  {
    name: "iFrameResizer",
    deps: ["vendor/iframeResizer.min"],
  },
];
